# Generated by Django 4.2.3 on 2023-07-04 15:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Requirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='Tipo de requisito')),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255, verbose_name='Empresa contratante')),
                ('title', models.CharField(max_length=255, verbose_name='Título da vaga')),
                ('salary_range', models.CharField(choices=[('Até R$ 1.000,00', 'Até R$ 1.000,00'), ('De R$ 1.000,01 a R$ 2.000,00', 'De R$ 1.000,01 a R$ 2.000,00'), ('De R$ 2.000,01 a R$ 3.000,00', 'De R$ 2.000,01 a R$ 3.000,00'), ('Acima de R$ 3.000,00', 'Acima de R$ 3.000,00')], max_length=45, verbose_name='Faixa salarial')),
                ('description', models.TextField(max_length=255, verbose_name='Descrição da vaga')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('requirements', models.ManyToManyField(to='app_company.requirements', verbose_name='Requisitos')),
            ],
        ),
        migrations.CreateModel(
            name='ContactCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager', models.CharField(max_length=45, verbose_name='Nome do responsável')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('cellphone', models.CharField(max_length=14, verbose_name='Número de celular')),
                ('commercial_phone', models.CharField(max_length=12, verbose_name='Número comercial')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_company.company')),
            ],
        ),
    ]
