# Generated by Django 4.2.3 on 2023-07-12 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_candidate', '0002_experience_user_remove_experience_name_and_more'),
        ('app_company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='candidate',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_candidate.candidate'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='salary_range',
            field=models.CharField(choices=[(1, 'Até R$ 1.000,00'), (2, 'De R$ 1.000,01 a R$ 2.000,00'), (3, 'De R$ 2.000,01 a R$ 3.000,00'), (4, 'Acima de R$ 3.000,00')], max_length=45, verbose_name='Faixa salarial'),
        ),
    ]
