# Generated by Django 4.2.3 on 2023-07-05 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='cnpj',
            field=models.CharField(default='0000000000000xx', max_length=14, unique=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='minimum_schooling',
            field=models.CharField(choices=[('Ensino Fundamental', 'Ensino Fundamental'), ('Ensino Médio', 'Ensino Médio'), ('Tecnólogo', 'Tecnólogo'), ('Ensino Superior', 'Ensino Superior'), ('Pós / MBA / Mestrado', 'Pós / MBA / Mestrado'), ('Doutorado', 'Doutorado')], max_length=45, null=True, verbose_name='Escolaridade'),
        ),
        migrations.AlterField(
            model_name='requirements',
            name='name',
            field=models.CharField(max_length=45, unique=True, verbose_name='Tipo de requisito'),
        ),
    ]
