# Generated by Django 4.2.3 on 2023-07-13 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_company', '0003_jobs_minimum_schooling_candidate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='minimum_schooling_candidate',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='salary_range_candidate',
        ),
    ]
