# Generated by Django 4.2.3 on 2023-07-13 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_candidate', '0002_experience_user_remove_experience_name_and_more'),
        ('app_company', '0004_remove_jobs_candidate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_schooling_candidate', models.CharField(choices=[(1, 'Ensino Fundamental'), (2, 'Ensino Médio'), (3, 'Tecnólogo'), (4, 'Ensino Superior'), (5, 'Pós / MBA / Mestrado'), (6, 'Doutorado')], max_length=45, null=True, verbose_name='Escolaridade')),
                ('salary_range_candidate', models.CharField(choices=[(1, 'Até R$ 1.000,00'), (2, 'De R$ 1.000,01 a R$ 2.000,00'), (3, 'De R$ 2.000,01 a R$ 3.000,00'), (4, 'Acima de R$ 3.000,00')], max_length=45, verbose_name='Faixa salarial')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_candidate.candidate', verbose_name='Candidato')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_company.jobs', verbose_name='Vaga')),
            ],
        ),
    ]
