# Generated by Django 4.2.3 on 2023-07-13 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_company', '0006_alter_application_candidate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_company.jobs', verbose_name='Vaga'),
        ),
    ]
