# Generated by Django 4.2.3 on 2023-07-14 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_company', '0008_alter_application_candidate'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
