# Generated by Django 4.2.3 on 2023-07-11 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_candidate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='experience',
            name='name',
        ),
        migrations.AddField(
            model_name='experience',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
